In [1]:
import pandas as pd

In [2]:
names=['Ramesh','Suresh','Sathish']

In [3]:
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish

In [10]:
pd.DataFrame(names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish

In [11]:
pd.DataFrame(names,['A','B','C'],['Names'])

     Names
A   Ramesh
B   Suresh
C  Sathish

In [19]:
#Create a dataframe using dictionary
age=[20,22,24]
d={'Names':names,'Age':age}
pd.DataFrame(d)

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [26]:
df=pd.DataFrame(d)
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [24]:
dictionary={'Ramesh':'20','Suresh':22,'Sathish':24}
pd.DataFrame(dictionary,index=['age'])

    Ramesh  Suresh  Sathish
age     20      22       24

In [27]:
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [28]:
df['city']

KeyError: 'city'

In [29]:
df['City']=['Hyd','Blr','Pune']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [30]:
df['Names']

0     Ramesh
1     Suresh
2    Sathish
Name: Names, dtype: str

In [31]:
df.replace('Suresh','Mahesh')

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   22   Blr
2  Sathish   24  Pune

In [32]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [33]:
df.replace('Suresh','Mahesh',inplace=True)
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   22   Blr
2  Sathish   24  Pune

Changing Mahesh's age from 22 to 26

In [34]:
l=[]
for i,j in zip(df['Names'],df['Age']):
    if i=='Mahesh':
        l.append(28)
    else:
        l.append(j)
df['Age']=l
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   28   Blr
2  Sathish   24  Pune

np.where

In [36]:
import numpy as np
df['Age']=np.where(df['Names']=='Mahesh',65,df['Age'])
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   65   Blr
2  Sathish   24  Pune

In [38]:
#dropping column
df.drop('City',axis=1)

     Names  Age
0   Ramesh   20
1   Mahesh   65
2  Sathish   24

In [39]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   65   Blr
2  Sathish   24  Pune

In [40]:
df.drop(2)

    Names  Age City
0  Ramesh   20  Hyd
1  Mahesh   65  Blr

In [41]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Mahesh   65   Blr
2  Sathish   24  Pune

In [43]:
df.drop(columns='City')

     Names  Age
0   Ramesh   20
1   Mahesh   65
2  Sathish   24